# Generated by Django 4.0.1 on 2022-01-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=20)),
                ('sana', models.DateField()),
                ('matn', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='rasmlar')),
                ('maqola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.maqola')),
            ],
        ),
    ]
